# Generated by Django 5.0.6 on 2025-11-13 08:41

import django.db.models.deletion
import lotto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='회차명')),
                ('open_at', models.DateTimeField(auto_now_add=True, verbose_name='판매 시작')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='판매 마감')),
                ('numbers', models.CharField(blank=True, default='', max_length=50, validators=[lotto.models.validate_numbers], verbose_name='당첨번호(6개)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='마감')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50, validators=[lotto.models.validate_numbers], verbose_name='선택번호(6개)')),
                ('is_auto', models.BooleanField(default=False, verbose_name='자동')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='등수')),
                ('prize', models.PositiveIntegerField(blank=True, null=True, verbose_name='상금')),
                ('matched', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='일치개수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lotto.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['draw', 'user'], name='lotto_order_draw_id_738e18_idx')],
            },
        ),
    ]
